/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MapRouteImport } from './routes/map'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileSavedRouteImport } from './routes/profile_.saved'
import { Route as ProfileHelpRouteImport } from './routes/profile_.help'
import { Route as ProfileCollectionsRouteImport } from './routes/profile_.collections'
import { Route as ChannelHandleRouteImport } from './routes/channel.$handle'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSavedRoute = ProfileSavedRouteImport.update({
  id: '/profile_/saved',
  path: '/profile/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHelpRoute = ProfileHelpRouteImport.update({
  id: '/profile_/help',
  path: '/profile/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCollectionsRoute = ProfileCollectionsRouteImport.update({
  id: '/profile_/collections',
  path: '/profile/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelHandleRoute = ChannelHandleRouteImport.update({
  id: '/channel/$handle',
  path: '/channel/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/following': typeof FollowingRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/submit': typeof SubmitRoute
  '/channel/$handle': typeof ChannelHandleRoute
  '/profile/collections': typeof ProfileCollectionsRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/saved': typeof ProfileSavedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/following': typeof FollowingRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/submit': typeof SubmitRoute
  '/channel/$handle': typeof ChannelHandleRoute
  '/profile/collections': typeof ProfileCollectionsRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/saved': typeof ProfileSavedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/following': typeof FollowingRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/submit': typeof SubmitRoute
  '/channel/$handle': typeof ChannelHandleRoute
  '/profile_/collections': typeof ProfileCollectionsRoute
  '/profile_/help': typeof ProfileHelpRoute
  '/profile_/saved': typeof ProfileSavedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/following'
    | '/map'
    | '/profile'
    | '/search'
    | '/submit'
    | '/channel/$handle'
    | '/profile/collections'
    | '/profile/help'
    | '/profile/saved'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/following'
    | '/map'
    | '/profile'
    | '/search'
    | '/submit'
    | '/channel/$handle'
    | '/profile/collections'
    | '/profile/help'
    | '/profile/saved'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/following'
    | '/map'
    | '/profile'
    | '/search'
    | '/submit'
    | '/channel/$handle'
    | '/profile_/collections'
    | '/profile_/help'
    | '/profile_/saved'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FollowingRoute: typeof FollowingRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SubmitRoute: typeof SubmitRoute
  ChannelHandleRoute: typeof ChannelHandleRoute
  ProfileCollectionsRoute: typeof ProfileCollectionsRoute
  ProfileHelpRoute: typeof ProfileHelpRoute
  ProfileSavedRoute: typeof ProfileSavedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/saved': {
      id: '/profile_/saved'
      path: '/profile/saved'
      fullPath: '/profile/saved'
      preLoaderRoute: typeof ProfileSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/help': {
      id: '/profile_/help'
      path: '/profile/help'
      fullPath: '/profile/help'
      preLoaderRoute: typeof ProfileHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/collections': {
      id: '/profile_/collections'
      path: '/profile/collections'
      fullPath: '/profile/collections'
      preLoaderRoute: typeof ProfileCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$handle': {
      id: '/channel/$handle'
      path: '/channel/$handle'
      fullPath: '/channel/$handle'
      preLoaderRoute: typeof ChannelHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FollowingRoute: FollowingRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SubmitRoute: SubmitRoute,
  ChannelHandleRoute: ChannelHandleRoute,
  ProfileCollectionsRoute: ProfileCollectionsRoute,
  ProfileHelpRoute: ProfileHelpRoute,
  ProfileSavedRoute: ProfileSavedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
